/**
 * AUTH
 */

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const CLEAR_LOGIN_MESSAGES = 'CLEAR_LOGIN_MESSAGES';

export const ADMIN_LOGIN_START = 'ADMIN_LOGIN_START';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const SET_ADMIN_AUTH_REDIRECT_PATH = 'SET_ADMIN_AUTH_REDIRECT_PATH';

/**
 * PAYMENT
 */
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';

/**
 * UI
 */
export const SHOW_SEARCH = 'SHOW_SEARCH';

/**
 * CART
 */

export const SET_CART_START = 'SET_CART_START';
export const SET_CART_SUCCESS = 'SET_CART_SUCCESS';
export const SET_CART_FAILED = 'SET_CART_FAILED';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const CLEAR_CART_MESSAGES = 'CLEAR_CART_MESSAGES';
export const CLEAR_PRODUCT_MESSAGES = 'CLEAR_PRODUCT_MESSAGES';

export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAILED = 'CLEAR_CART_FAILED';

/**
 * PRODUCTS
 */

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

// export const ADD_PRODUCT_START = 'ADD_PRODUCT_START'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

// export const UPLOAD_PRODUCT_IMAGE_START = 'UPLOAD_PRODUCT_IMAGE_START';
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = 'UPLOAD_PRODUCT_IMAGE_SUCCESS';
export const UPLOAD_PRODUCT_IMAGE_FAILED = 'UPLOAD_PRODUCT_IMAGE_FAILED';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';





export const GET_ORDERS_ADMIN_SUCCESS = 'GET_ORDERS_ADMIN_SUCCESS';
export const GET_ORDERS_ADMIN_FAILED = 'GET_ORDERS_ADMIN_FAILED'

export const GET_ORDERS_CUSTOMER_SUCCESS = 'GET_ORDERS_CUSTOMER_SUCCESS';
export const GET_ORDERS_CUSTOMER_FAILED = 'GET_ORDERS_CUSTOMER_FAILED';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';

export const CLEAR_ORDER_MESSAGES = 'CLEAR_ORDER_MESSAGES';